config/routes.rb
NestedFormFailing::Application.routes.draw do
  resources :gifts

  resources :birthdays

  resources :people
  root :to => 'people#new'

end

app/models/birthday.rb
class Birthday < ActiveRecord::Base
  attr_accessible :when, :gifts_attributes
  has_many :gifts

  accepts_nested_attributes_for :gifts
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  attr_accessible :name

  belongs_to :birthday
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name, :birthday_attributes

  belongs_to :birthday
  accepts_nested_attributes_for :birthday
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/birthdays_controller.rb
class BirthdaysController < ApplicationController
  # GET /birthdays
  # GET /birthdays.json
  def index
    @birthdays = Birthday.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @birthdays }
    end
  end

  # GET /birthdays/1
  # GET /birthdays/1.json
  def show
    @birthday = Birthday.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @birthday }
    end
  end

  # GET /birthdays/new
  # GET /birthdays/new.json
  def new
    @birthday = Birthday.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @birthday }
    end
  end

  # GET /birthdays/1/edit
  def edit
    @birthday = Birthday.find(params[:id])
  end

  # POST /birthdays
  # POST /birthdays.json
  def create
    @birthday = Birthday.new(params[:birthday])

    respond_to do |format|
      if @birthday.save
        format.html { redirect_to @birthday, notice: 'Birthday was successfully created.' }
        format.json { render json: @birthday, status: :created, location: @birthday }
      else
        format.html { render action: "new" }
        format.json { render json: @birthday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /birthdays/1
  # PUT /birthdays/1.json
  def update
    @birthday = Birthday.find(params[:id])

    respond_to do |format|
      if @birthday.update_attributes(params[:birthday])
        format.html { redirect_to @birthday, notice: 'Birthday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @birthday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birthdays/1
  # DELETE /birthdays/1.json
  def destroy
    @birthday = Birthday.find(params[:id])
    @birthday.destroy

    respond_to do |format|
      format.html { redirect_to birthdays_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gifts }
    end
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
    @gift = Gift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gift }
    end
  end

  # GET /gifts/new
  # GET /gifts/new.json
  def new
    @gift = Gift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gift }
    end
  end

  # GET /gifts/1/edit
  def edit
    @gift = Gift.find(params[:id])
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(params[:gift])

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render json: @gift, status: :created, location: @gift }
      else
        format.html { render action: "new" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gifts/1
  # PUT /gifts/1.json
  def update
    @gift = Gift.find(params[:id])

    respond_to do |format|
      if @gift.update_attributes(params[:gift])
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy

    respond_to do |format|
      format.html { redirect_to gifts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new
    @person.build_birthday
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birthdays_helper.rb
module BirthdaysHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/birthdays/_form.html.erb
<%= form_for(@birthday) do |f| %>
  <% if @birthday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@birthday.errors.count, "error") %> prohibited this birthday from being saved:</h2>

      <ul>
      <% @birthday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :when %><br />
    <%= f.text_field :when %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birthdays/edit.html.erb
<h1>Editing birthday</h1>

<%= render 'form' %>

<%= link_to 'Show', @birthday %> |
<%= link_to 'Back', birthdays_path %>

app/views/birthdays/index.html.erb
<h1>Listing birthdays</h1>

<table>
  <tr>
    <th>When</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @birthdays.each do |birthday| %>
  <tr>
    <td><%= birthday.when %></td>
    <td><%= link_to 'Show', birthday %></td>
    <td><%= link_to 'Edit', edit_birthday_path(birthday) %></td>
    <td><%= link_to 'Destroy', birthday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Birthday', new_birthday_path %>

app/views/birthdays/new.html.erb
<h1>New birthday</h1>

<%= render 'form' %>

<%= link_to 'Back', birthdays_path %>

app/views/birthdays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>When:</b>
  <%= @birthday.when %>
</p>


<%= link_to 'Edit', edit_birthday_path(@birthday) %> |
<%= link_to 'Back', birthdays_path %>

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birthday_id %><br />
    <%= f.number_field :birthday_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<h1>Listing gifts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Birthday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gifts.each do |gift| %>
  <tr>
    <td><%= gift.name %></td>
    <td><%= gift.birthday_id %></td>
    <td><%= link_to 'Show', gift %></td>
    <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
    <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>New gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gift.name %>
</p>

<p>
  <b>Birthday:</b>
  <%= @gift.birthday_id %>
</p>


<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedFormFailing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= nested_form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :birthday do |bday| %>
    <%= bday.fields_for :gifts do |gift| %>
      <%= render 'gifts_fields', f: gift %>
    <% end %>
    <%= bday.link_to_add 'Add Gift', :gifts %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_gifts_fields.html.erb
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  <%= f.link_to_remove "Remove this gift" %>
</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Birthday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.birthday_id %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Birthday:</b>
  <%= @person.birthday_id %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>